// Mocks generated by Mockito 5.4.3 from annotations
// in cloudwalk_test/test/app/modules/home/home_store_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i5;

import 'package:cloudwalk_test/app/modules/home/interfaces/ihttp_client.dart'
    as _i2;
import 'package:cloudwalk_test/app/modules/home/interfaces/ilocal_db_client.dart'
    as _i3;
import 'package:cloudwalk_test/app/modules/home/repositories/nasa_api_repository.dart'
    as _i8;
import 'package:cloudwalk_test/app/modules/home/repositories/nasa_db_local_repository.dart'
    as _i10;
import 'package:cloudwalk_test/app/modules/home/services/dio_client.dart'
    as _i7;
import 'package:cloudwalk_test/app/shared/models/nasa_apod_model.dart' as _i9;
import 'package:connectivity_plus/connectivity_plus.dart' as _i4;
import 'package:connectivity_plus_platform_interface/connectivity_plus_platform_interface.dart'
    as _i6;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeIHttpClient_0 extends _i1.SmartFake implements _i2.IHttpClient {
  _FakeIHttpClient_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeILocalDbClient_1 extends _i1.SmartFake
    implements _i3.ILocalDbClient {
  _FakeILocalDbClient_1(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [Connectivity].
///
/// See the documentation for Mockito's code generation for more information.
class MockConnectivity extends _i1.Mock implements _i4.Connectivity {
  MockConnectivity() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i5.Stream<_i6.ConnectivityResult> get onConnectivityChanged =>
      (super.noSuchMethod(
        Invocation.getter(#onConnectivityChanged),
        returnValue: _i5.Stream<_i6.ConnectivityResult>.empty(),
      ) as _i5.Stream<_i6.ConnectivityResult>);

  @override
  _i5.Future<_i6.ConnectivityResult> checkConnectivity() => (super.noSuchMethod(
        Invocation.method(
          #checkConnectivity,
          [],
        ),
        returnValue: _i5.Future<_i6.ConnectivityResult>.value(
            _i6.ConnectivityResult.bluetooth),
      ) as _i5.Future<_i6.ConnectivityResult>);
}

/// A class which mocks [DioClient].
///
/// See the documentation for Mockito's code generation for more information.
class MockDioClient extends _i1.Mock implements _i7.DioClient {
  MockDioClient() {
    _i1.throwOnMissingStub(this);
  }
}

/// A class which mocks [NasaApiRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockNasaApiRepository extends _i1.Mock implements _i8.NasaApiRepository {
  @override
  _i2.IHttpClient get client => (super.noSuchMethod(
        Invocation.getter(#client),
        returnValue: _FakeIHttpClient_0(
          this,
          Invocation.getter(#client),
        ),
        returnValueForMissingStub: _FakeIHttpClient_0(
          this,
          Invocation.getter(#client),
        ),
      ) as _i2.IHttpClient);

  @override
  _i5.Future<List<_i9.NasaApodModel>?> getApodList(String? startDate) =>
      (super.noSuchMethod(
        Invocation.method(
          #getApodList,
          [startDate],
        ),
        returnValue: _i5.Future<List<_i9.NasaApodModel>?>.value(),
        returnValueForMissingStub: _i5.Future<List<_i9.NasaApodModel>?>.value(),
      ) as _i5.Future<List<_i9.NasaApodModel>?>);
}

/// A class which mocks [NasaDbLocalRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockNasaDbLocalRepository extends _i1.Mock
    implements _i10.NasaDbLocalRepository {
  @override
  _i3.ILocalDbClient get dbClient => (super.noSuchMethod(
        Invocation.getter(#dbClient),
        returnValue: _FakeILocalDbClient_1(
          this,
          Invocation.getter(#dbClient),
        ),
        returnValueForMissingStub: _FakeILocalDbClient_1(
          this,
          Invocation.getter(#dbClient),
        ),
      ) as _i3.ILocalDbClient);

  @override
  dynamic addAll(List<_i9.NasaApodModel>? list) => super.noSuchMethod(
        Invocation.method(
          #addAll,
          [list],
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i5.Future<List<_i9.NasaApodModel>> getList() => (super.noSuchMethod(
        Invocation.method(
          #getList,
          [],
        ),
        returnValue:
            _i5.Future<List<_i9.NasaApodModel>>.value(<_i9.NasaApodModel>[]),
        returnValueForMissingStub:
            _i5.Future<List<_i9.NasaApodModel>>.value(<_i9.NasaApodModel>[]),
      ) as _i5.Future<List<_i9.NasaApodModel>>);

  @override
  _i5.Future<bool> verifyDbIsNotEmpty() => (super.noSuchMethod(
        Invocation.method(
          #verifyDbIsNotEmpty,
          [],
        ),
        returnValue: _i5.Future<bool>.value(false),
        returnValueForMissingStub: _i5.Future<bool>.value(false),
      ) as _i5.Future<bool>);
}
